[package]
name = "lstime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono= "0.4"
tui = { version = "0.14", default-features = false, features = ['crossterm', 'serde'] }
